name: ci

on:
  push:
  pull_request:

jobs:
  firmware-build-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run -e cyd

      - name: Run native unit tests
        run: pio test -e native
